[package]
name = "pexp_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
argh = "0.1.9"
dirs = "4.0.0"
nix = "0.26.1"
notify = "5.0.0"
shell-quote = "0.3.0"
